/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'LocateMsg'
 * message type.
 */

public class LocateMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 44;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 8;

    /** Create a new LocateMsg of size 44. */
    public LocateMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new LocateMsg of the given data_length. */
    public LocateMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new LocateMsg with the given data_length
     * and base offset.
     */
    public LocateMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new LocateMsg using the given byte array
     * as backing store.
     */
    public LocateMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new LocateMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public LocateMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new LocateMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public LocateMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new LocateMsg embedded in the given message
     * at the given base offset.
     */
    public LocateMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new LocateMsg embedded in the given message
     * at the given base offset and length.
     */
    public LocateMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <LocateMsg> \n";
      try {
        s += "  [nodeId=0x"+Long.toHexString(get_nodeId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [seqNo=0x"+Long.toHexString(get_seqNo())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rssi=";
        for (int i = 0; i < 40; i++) {
          s += "0x"+Long.toHexString(getElement_rssi(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodeId
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodeId' is signed (false).
     */
    public static boolean isSigned_nodeId() {
        return false;
    }

    /**
     * Return whether the field 'nodeId' is an array (false).
     */
    public static boolean isArray_nodeId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nodeId'
     */
    public static int offset_nodeId() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodeId'
     */
    public static int offsetBits_nodeId() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'nodeId'
     */
    public int get_nodeId() {
        return (int)getUIntBEElement(offsetBits_nodeId(), 16);
    }

    /**
     * Set the value of the field 'nodeId'
     */
    public void set_nodeId(int value) {
        setUIntBEElement(offsetBits_nodeId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'nodeId'
     */
    public static int size_nodeId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nodeId'
     */
    public static int sizeBits_nodeId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: seqNo
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'seqNo' is signed (false).
     */
    public static boolean isSigned_seqNo() {
        return false;
    }

    /**
     * Return whether the field 'seqNo' is an array (false).
     */
    public static boolean isArray_seqNo() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'seqNo'
     */
    public static int offset_seqNo() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'seqNo'
     */
    public static int offsetBits_seqNo() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'seqNo'
     */
    public int get_seqNo() {
        return (int)getUIntBEElement(offsetBits_seqNo(), 16);
    }

    /**
     * Set the value of the field 'seqNo'
     */
    public void set_seqNo(int value) {
        setUIntBEElement(offsetBits_seqNo(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'seqNo'
     */
    public static int size_seqNo() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'seqNo'
     */
    public static int sizeBits_seqNo() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rssi
    //   Field type: short[], unsigned
    //   Offset (bits): 32
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rssi' is signed (false).
     */
    public static boolean isSigned_rssi() {
        return false;
    }

    /**
     * Return whether the field 'rssi' is an array (true).
     */
    public static boolean isArray_rssi() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'rssi'
     */
    public static int offset_rssi(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 40) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rssi'
     */
    public static int offsetBits_rssi(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 40) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'rssi' as a short[]
     */
    public short[] get_rssi() {
        short[] tmp = new short[40];
        for (int index0 = 0; index0 < numElements_rssi(0); index0++) {
            tmp[index0] = getElement_rssi(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'rssi' from the given short[]
     */
    public void set_rssi(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_rssi(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'rssi'
     */
    public short getElement_rssi(int index1) {
        return (short)getUIntBEElement(offsetBits_rssi(index1), 8);
    }

    /**
     * Set an element of the array 'rssi'
     */
    public void setElement_rssi(int index1, short value) {
        setUIntBEElement(offsetBits_rssi(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'rssi'
     */
    public static int totalSize_rssi() {
        return (320 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'rssi'
     */
    public static int totalSizeBits_rssi() {
        return 320;
    }

    /**
     * Return the size, in bytes, of each element of the array 'rssi'
     */
    public static int elementSize_rssi() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'rssi'
     */
    public static int elementSizeBits_rssi() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'rssi'
     */
    public static int numDimensions_rssi() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'rssi'
     */
    public static int numElements_rssi() {
        return 40;
    }

    /**
     * Return the number of elements in the array 'rssi'
     * for the given dimension.
     */
    public static int numElements_rssi(int dimension) {
      int array_dims[] = { 40,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'rssi' with a String
     */
    public void setString_rssi(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_rssi(i, (short)s.charAt(i));
         }
         setElement_rssi(i, (short)0); //null terminate
    }

    /**
     * Read the array 'rssi' as a String
     */
    public String getString_rssi() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,40)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_rssi(i) == (char)0) break;
             carr[i] = (char)getElement_rssi(i);
         }
         return new String(carr,0,i);
    }

}
